
local MyGameReq = {
    GAME_START_INFO={
        lengthMap = {
            [1] = 32,
            [17] = {maxlen = 4},
            [32] = {maxlen = 8},
            [33] = {maxlen = 2},
            [34] = {maxlen = 32},
            [35] = {maxlen = 36,maxwidth = 2,complexType = 'matrix2'},
            [36] = {maxlen = 2},
            [37] = {maxlen = 4},
            [46] = {maxlen = 3},
            [47] = {maxlen = 3},
            [48] = {maxlen = 3},
            maxlen = 48
        },
        nameMap = {
            'szSerialNO',
            'nBoutCount',
            'nBaseDeposit',
            'nBaseScore',
            'nBanker',
            'nBankerHold',
            'nCurrentChair',
            'dwStatus',
            'dwCurrentFlags',
            'nFirstCatch',
            'nFirstThrow',
            'nThrowWait',
            'nMaxAutoThrow',
            'nEntrustWait',
            'bNeedDeposit',
            'bForbidDesert',
            'nDices',
            'bQuickCatch',
            'bAllowChi',
            'bAnGangShow',
            'bJokerSortIn',
            'bBaibanNoSort',
            'nBeginNO',
            'nJokerNO',
            'nJokerID',
            'nJokerID2',
            'nFanID',
            'nTailTaken',
            'nCurrentCatch',
            'nPGCHWait',
            'nPGCHWaitEx',
            'nReserved',
            'nCardsCount',
            'nChairCards',
            'nHuaCards',
            'nHuaCount',
            'nReserved1',
            'nRoleID',
            'nRandRoleDouble',
            'nQuan',
            'bLian',
            'bKaiQiDiBao',
            'nDiBaoActiveID',
            'nQiHu',
            'bKaiqiHuanPaiDiscount',
            'nHuanPaiDiscount',
            'nHuanPaiStart',
            'nHuanPaiEnd'
        },
        formatKey = '<AiiiiiiLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<A32iiiiiiLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 712
    },

    GAME_TABLE_INFO={
        lengthMap = {
            [1] = 32,
            [17] = {maxlen = 4},
            [32] = {maxlen = 8},
            [33] = {maxlen = 4},
            [35] = {maxlen = 2},
            [36] = {maxlen = 4},
            [38] = {maxlen = 2},
            [39] = {maxlen = 4},
            [41] = {maxlen = 2},
            [42] = {maxlen = 4},
            [44] = {maxlen = 2},
            [45] = {maxlen = 4},
            [47] = {maxlen = 2},
            [48] = {maxlen = 4},
            [50] = {maxlen = 2},
            [51] = {maxlen = 4},
            [53] = {maxlen = 2},
            [54] = {maxlen = 4},
            [56] = {maxlen = 2},
            [57] = {maxlen = 4},
            [59] = {maxlen = 2},
            [60] = {maxlen = 4},
            [62] = {maxlen = 2},
            [63] = {maxlen = 4},
            [65] = {maxlen = 2},
            [66] = {maxlen = 4},
            [68] = {maxlen = 2},
            [69] = {maxlen = 4},
            [71] = {maxlen = 2},
            [72] = {maxlen = 4},
            [74] = {maxlen = 2},
            [75] = {maxlen = 4},
            [77] = {maxlen = 2},
            [78] = {maxlen = 4},
            [80] = {maxlen = 2},
            [81] = {maxlen = 4},
            [83] = {maxlen = 2},
            [84] = {maxlen = 4},
            [86] = {maxlen = 2},
            [87] = {maxlen = 4},
            [89] = {maxlen = 2},
            [90] = {maxlen = 4},
            [92] = {maxlen = 2},
            [93] = {maxlen = 4},
            [95] = {maxlen = 2},
            [96] = {maxlen = 4},
            [98] = {maxlen = 2},
            [99] = {maxlen = 4},
            [101] = {maxlen = 2},
            [102] = {maxlen = 4},
            [104] = {maxlen = 2},
            [105] = {maxlen = 4},
            [106] = {maxlen = 4},
            [108] = {maxlen = 2},
            [109] = {maxlen = 4},
            [111] = {maxlen = 2},
            [112] = {maxlen = 4},
            [114] = {maxlen = 2},
            [115] = {maxlen = 4},
            [117] = {maxlen = 2},
            [118] = {maxlen = 4},
            [120] = {maxlen = 2},
            [121] = {maxlen = 4},
            [123] = {maxlen = 2},
            [124] = {maxlen = 4},
            [126] = {maxlen = 2},
            [127] = {maxlen = 4},
            [129] = {maxlen = 2},
            [130] = {maxlen = 4},
            [132] = {maxlen = 2},
            [133] = {maxlen = 4},
            [135] = {maxlen = 2},
            [136] = {maxlen = 4},
            [138] = {maxlen = 2},
            [139] = {maxlen = 4},
            [141] = {maxlen = 2},
            [142] = {maxlen = 4},
            [144] = {maxlen = 2},
            [145] = {maxlen = 4},
            [147] = {maxlen = 2},
            [148] = {maxlen = 4},
            [150] = {maxlen = 2},
            [151] = {maxlen = 4},
            [153] = {maxlen = 2},
            [154] = {maxlen = 4},
            [156] = {maxlen = 2},
            [157] = {maxlen = 4},
            [159] = {maxlen = 2},
            [160] = {maxlen = 4},
            [162] = {maxlen = 2},
            [163] = {maxlen = 4},
            [165] = {maxlen = 2},
            [166] = {maxlen = 4},
            [168] = {maxlen = 2},
            [169] = {maxlen = 4},
            [171] = {maxlen = 2},
            [172] = {maxlen = 4},
            [174] = {maxlen = 2},
            [175] = {maxlen = 4},
            [177] = {maxlen = 2},
            [178] = {maxlen = 4},
            [179] = {maxlen = 4},
            [181] = {maxlen = 2},
            [182] = {maxlen = 4},
            [184] = {maxlen = 2},
            [185] = {maxlen = 4},
            [187] = {maxlen = 2},
            [188] = {maxlen = 4},
            [190] = {maxlen = 2},
            [191] = {maxlen = 4},
            [193] = {maxlen = 2},
            [194] = {maxlen = 4},
            [196] = {maxlen = 2},
            [197] = {maxlen = 4},
            [199] = {maxlen = 2},
            [200] = {maxlen = 4},
            [202] = {maxlen = 2},
            [203] = {maxlen = 4},
            [205] = {maxlen = 2},
            [206] = {maxlen = 4},
            [208] = {maxlen = 2},
            [209] = {maxlen = 4},
            [211] = {maxlen = 2},
            [212] = {maxlen = 4},
            [214] = {maxlen = 2},
            [215] = {maxlen = 4},
            [217] = {maxlen = 2},
            [218] = {maxlen = 4},
            [220] = {maxlen = 2},
            [221] = {maxlen = 4},
            [223] = {maxlen = 2},
            [224] = {maxlen = 4},
            [226] = {maxlen = 2},
            [227] = {maxlen = 4},
            [229] = {maxlen = 2},
            [230] = {maxlen = 4},
            [232] = {maxlen = 2},
            [233] = {maxlen = 4},
            [235] = {maxlen = 2},
            [236] = {maxlen = 4},
            [238] = {maxlen = 2},
            [239] = {maxlen = 4},
            [241] = {maxlen = 2},
            [242] = {maxlen = 4},
            [244] = {maxlen = 2},
            [245] = {maxlen = 4},
            [247] = {maxlen = 2},
            [248] = {maxlen = 4},
            [250] = {maxlen = 2},
            [251] = {maxlen = 4},
            [252] = {maxlen = 4},
            [254] = {maxlen = 2},
            [255] = {maxlen = 4},
            [257] = {maxlen = 2},
            [258] = {maxlen = 4},
            [260] = {maxlen = 2},
            [261] = {maxlen = 4},
            [263] = {maxlen = 2},
            [264] = {maxlen = 4},
            [266] = {maxlen = 2},
            [267] = {maxlen = 4},
            [269] = {maxlen = 2},
            [270] = {maxlen = 4},
            [272] = {maxlen = 2},
            [273] = {maxlen = 4},
            [275] = {maxlen = 2},
            [276] = {maxlen = 4},
            [278] = {maxlen = 2},
            [279] = {maxlen = 4},
            [281] = {maxlen = 2},
            [282] = {maxlen = 4},
            [284] = {maxlen = 2},
            [285] = {maxlen = 4},
            [287] = {maxlen = 2},
            [288] = {maxlen = 4},
            [290] = {maxlen = 2},
            [291] = {maxlen = 4},
            [293] = {maxlen = 2},
            [294] = {maxlen = 4},
            [296] = {maxlen = 2},
            [297] = {maxlen = 4},
            [299] = {maxlen = 2},
            [300] = {maxlen = 4},
            [302] = {maxlen = 2},
            [303] = {maxlen = 4},
            [305] = {maxlen = 2},
            [306] = {maxlen = 4},
            [308] = {maxlen = 2},
            [309] = {maxlen = 4},
            [311] = {maxlen = 2},
            [312] = {maxlen = 4},
            [314] = {maxlen = 2},
            [315] = {maxlen = 4},
            [317] = {maxlen = 2},
            [318] = {maxlen = 4},
            [320] = {maxlen = 2},
            [321] = {maxlen = 4},
            [323] = {maxlen = 2},
            [324] = {maxlen = 4},
            [325] = {maxlen = 4},
            [327] = {maxlen = 2},
            [328] = {maxlen = 4},
            [330] = {maxlen = 2},
            [331] = {maxlen = 4},
            [333] = {maxlen = 2},
            [334] = {maxlen = 4},
            [336] = {maxlen = 2},
            [337] = {maxlen = 4},
            [339] = {maxlen = 2},
            [340] = {maxlen = 4},
            [342] = {maxlen = 2},
            [343] = {maxlen = 4},
            [345] = {maxlen = 2},
            [346] = {maxlen = 4},
            [348] = {maxlen = 2},
            [349] = {maxlen = 4},
            [351] = {maxlen = 2},
            [352] = {maxlen = 4},
            [354] = {maxlen = 2},
            [355] = {maxlen = 4},
            [357] = {maxlen = 2},
            [358] = {maxlen = 4},
            [360] = {maxlen = 2},
            [361] = {maxlen = 4},
            [363] = {maxlen = 2},
            [364] = {maxlen = 4},
            [366] = {maxlen = 2},
            [367] = {maxlen = 4},
            [369] = {maxlen = 2},
            [370] = {maxlen = 4},
            [372] = {maxlen = 2},
            [373] = {maxlen = 4},
            [375] = {maxlen = 2},
            [376] = {maxlen = 4},
            [378] = {maxlen = 2},
            [379] = {maxlen = 4},
            [381] = {maxlen = 2},
            [382] = {maxlen = 4},
            [384] = {maxlen = 2},
            [385] = {maxlen = 4},
            [387] = {maxlen = 2},
            [388] = {maxlen = 4},
            [390] = {maxlen = 2},
            [391] = {maxlen = 4},
            [393] = {maxlen = 2},
            [394] = {maxlen = 4},
            [396] = {maxlen = 2},
            [397] = {maxlen = 4},
            [398] = {maxlen = 36,maxwidth = 4,complexType = 'matrix2'},
            [399] = {maxlen = 4},
            [400] = {maxlen = 36,maxwidth = 4,complexType = 'matrix2'},
            [401] = {maxlen = 4},
            [402] = {maxlen = 8},
            [403] = {maxlen = 2},
            [404] = {maxlen = 32},
            [405] = {maxlen = 2},
            [407] = {maxlen = 30,maxwidth = 8,complexType = 'matrix2'},
            [408] = {maxlen = 8},
            [409] = {maxlen = 2},
            [410] = {maxlen = 8},
            [411] = {maxlen = 2},
            [416] = {maxlen = 2},
            [419] = {maxlen = 10},
            [420] = {maxlen = 10},
            [421] = {maxlen = 10},
            [423] = {maxlen = 2},
            [424] = {maxlen = 4},
            [429] = {maxlen = 3},
            [430] = {maxlen = 3},
            [431] = {maxlen = 3},
            maxlen = 431
        },
        nameMap = {
            'szSerialNO',
            'nBoutCount',
            'nBaseDeposit',
            'nBaseScore',
            'nBanker',
            'nBankerHold',
            'nCurrentChair',
            'dwStatus',
            'dwCurrentFlags',
            'nFirstCatch',
            'nFirstThrow',
            'nThrowWait',
            'nMaxAutoThrow',
            'nEntrustWait',
            'bNeedDeposit',
            'bForbidDesert',
            'nDices',
            'bQuickCatch',
            'bAllowChi',
            'bAnGangShow',
            'bJokerSortIn',
            'bBaibanNoSort',
            'nBeginNO',
            'nJokerNO',
            'nJokerID',
            'nJokerID2',
            'nFanID',
            'nTailTaken',
            'nCurrentCatch',
            'nPGCHWait',
            'nPGCHWaitEx',
            'nReserved',
            'nPengCardIDs11',
            'nPengCardChair11',
            'nPengReserved11',
            'nPengCardIDs12',
            'nPengCardChair12',
            'nPengReserved12',
            'nPengCardIDs13',
            'nPengCardChair13',
            'nPengReserved13',
            'nPengCardIDs14',
            'nPengCardChair14',
            'nPengReserved14',
            'nPengCardIDs15',
            'nPengCardChair15',
            'nPengReserved15',
            'nPengCardIDs16',
            'nPengCardChair16',
            'nPengReserved16',
            'nPengCardIDs21',
            'nPengCardChair21',
            'nPengReserved21',
            'nPengCardIDs22',
            'nPengCardChair22',
            'nPengReserved22',
            'nPengCardIDs23',
            'nPengCardChair23',
            'nPengReserved23',
            'nPengCardIDs24',
            'nPengCardChair24',
            'nPengReserved24',
            'nPengCardIDs25',
            'nPengCardChair25',
            'nPengReserved25',
            'nPengCardIDs26',
            'nPengCardChair26',
            'nPengReserved26',
            'nPengCardIDs31',
            'nPengCardChair31',
            'nPengReserved31',
            'nPengCardIDs32',
            'nPengCardChair32',
            'nPengReserved32',
            'nPengCardIDs33',
            'nPengCardChair33',
            'nPengReserved33',
            'nPengCardIDs34',
            'nPengCardChair34',
            'nPengReserved34',
            'nPengCardIDs35',
            'nPengCardChair35',
            'nPengReserved35',
            'nPengCardIDs36',
            'nPengCardChair36',
            'nPengReserved36',
            'nPengCardIDs41',
            'nPengCardChair41',
            'nPengReserved41',
            'nPengCardIDs42',
            'nPengCardChair42',
            'nPengReserved42',
            'nPengCardIDs43',
            'nPengCardChair43',
            'nPengReserved43',
            'nPengCardIDs44',
            'nPengCardChair44',
            'nPengReserved44',
            'nPengCardIDs45',
            'nPengCardChair45',
            'nPengReserved45',
            'nPengCardIDs46',
            'nPengCardChair46',
            'nPengReserved46',
            'nPengCount',
            'nChiCardIDs11',
            'nChiCardChair11',
            'nChiReserved11',
            'nChiCardIDs12',
            'nChiCardChair12',
            'nChiReserved12',
            'nChiCardIDs13',
            'nChiCardChair13',
            'nChiReserved13',
            'nChiCardIDs14',
            'nChiCardChair14',
            'nChiReserved14',
            'nChiCardIDs15',
            'nChiCardChair15',
            'nChiReserved15',
            'nChiCardIDs16',
            'nChiCardChair16',
            'nChiReserved16',
            'nChiCardIDs21',
            'nChiCardChair21',
            'nChiReserved21',
            'nChiCardIDs22',
            'nChiCardChair22',
            'nChiReserved22',
            'nChiCardIDs23',
            'nChiCardChair23',
            'nChiReserved23',
            'nChiCardIDs24',
            'nChiCardChair24',
            'nChiReserved24',
            'nChiCardIDs25',
            'nChiCardChair25',
            'nChiReserved25',
            'nChiCardIDs26',
            'nChiCardChair26',
            'nChiReserved26',
            'nChiCardIDs31',
            'nChiCardChair31',
            'nChiReserved31',
            'nChiCardIDs32',
            'nChiCardChair32',
            'nChiReserved32',
            'nChiCardIDs33',
            'nChiCardChair33',
            'nChiReserved33',
            'nChiCardIDs34',
            'nChiCardChair34',
            'nChiReserved34',
            'nChiCardIDs35',
            'nChiCardChair35',
            'nChiReserved35',
            'nChiCardIDs36',
            'nChiCardChair36',
            'nChiReserved36',
            'nChiCardIDs41',
            'nChiCardChair41',
            'nChiReserved41',
            'nChiCardIDs42',
            'nChiCardChair42',
            'nChiReserved42',
            'nChiCardIDs43',
            'nChiCardChair43',
            'nChiReserved43',
            'nChiCardIDs44',
            'nChiCardChair44',
            'nChiReserved44',
            'nChiCardIDs45',
            'nChiCardChair45',
            'nChiReserved45',
            'nChiCardIDs46',
            'nChiCardChair46',
            'nChiReserved46',
            'nChiCount',
            'nMnGangCardIDs11',
            'nMnGangCardChair11',
            'nMnGangReserved11',
            'nMnGangCardIDs12',
            'nMnGangCardChair12',
            'nMnGangReserved12',
            'nMnGangCardIDs13',
            'nMnGangCardChair13',
            'nMnGangReserved13',
            'nMnGangCardIDs14',
            'nMnGangCardChair14',
            'nMnGangReserved14',
            'nMnGangCardIDs15',
            'nMnGangCardChair15',
            'nMnGangReserved15',
            'nMnGangCardIDs16',
            'nMnGangCardChair16',
            'nMnGangReserved16',
            'nMnGangCardIDs21',
            'nMnGangCardChair21',
            'nMnGangReserved21',
            'nMnGangCardIDs22',
            'nMnGangCardChair22',
            'nMnGangReserved22',
            'nMnGangCardIDs23',
            'nMnGangCardChair23',
            'nMnGangReserved23',
            'nMnGangCardIDs24',
            'nMnGangCardChair24',
            'nMnGangReserved24',
            'nMnGangCardIDs25',
            'nMnGangCardChair25',
            'nMnGangReserved25',
            'nMnGangCardIDs26',
            'nMnGangCardChair26',
            'nMnGangReserved26',
            'nMnGangCardIDs31',
            'nMnGangCardChair31',
            'nMnGangReserved31',
            'nMnGangCardIDs32',
            'nMnGangCardChair32',
            'nMnGangReserved32',
            'nMnGangCardIDs33',
            'nMnGangCardChair33',
            'nMnGangReserved33',
            'nMnGangCardIDs34',
            'nMnGangCardChair34',
            'nMnGangReserved34',
            'nMnGangCardIDs35',
            'nMnGangCardChair35',
            'nMnGangReserved35',
            'nMnGangCardIDs36',
            'nMnGangCardChair36',
            'nMnGangReserved36',
            'nMnGangCardIDs41',
            'nMnGangCardChair41',
            'nMnGangReserved41',
            'nMnGangCardIDs42',
            'nMnGangCardChair42',
            'nMnGangReserved42',
            'nMnGangCardIDs43',
            'nMnGangCardChair43',
            'nMnGangReserved43',
            'nMnGangCardIDs44',
            'nMnGangCardChair44',
            'nMnGangReserved44',
            'nMnGangCardIDs45',
            'nMnGangCardChair45',
            'nMnGangReserved45',
            'nMnGangCardIDs46',
            'nMnGangCardChair46',
            'nMnGangReserved46',
            'nMnGangCount',
            'nAnGangCardIDs11',
            'nAnGangCardChair11',
            'nAnGangReserved11',
            'nAnGangCardIDs12',
            'nAnGangCardChair12',
            'nAnGangReserved12',
            'nAnGangCardIDs13',
            'nAnGangCardChair13',
            'nAnGangReserved13',
            'nAnGangCardIDs14',
            'nAnGangCardChair14',
            'nAnGangReserved14',
            'nAnGangCardIDs15',
            'nAnGangCardChair15',
            'nAnGangReserved15',
            'nAnGangCardIDs16',
            'nAnGangCardChair16',
            'nAnGangReserved16',
            'nAnGangCardIDs21',
            'nAnGangCardChair21',
            'nAnGangReserved21',
            'nAnGangCardIDs22',
            'nAnGangCardChair22',
            'nAnGangReserved22',
            'nAnGangCardIDs23',
            'nAnGangCardChair23',
            'nAnGangReserved23',
            'nAnGangCardIDs24',
            'nAnGangCardChair24',
            'nAnGangReserved24',
            'nAnGangCardIDs25',
            'nAnGangCardChair25',
            'nAnGangReserved25',
            'nAnGangCardIDs26',
            'nAnGangCardChair26',
            'nAnGangReserved26',
            'nAnGangCardIDs31',
            'nAnGangCardChair31',
            'nAnGangReserved31',
            'nAnGangCardIDs32',
            'nAnGangCardChair32',
            'nAnGangReserved32',
            'nAnGangCardIDs33',
            'nAnGangCardChair33',
            'nAnGangReserved33',
            'nAnGangCardIDs34',
            'nAnGangCardChair34',
            'nAnGangReserved34',
            'nAnGangCardIDs35',
            'nAnGangCardChair35',
            'nAnGangReserved35',
            'nAnGangCardIDs36',
            'nAnGangCardChair36',
            'nAnGangReserved36',
            'nAnGangCardIDs41',
            'nAnGangCardChair41',
            'nAnGangReserved41',
            'nAnGangCardIDs42',
            'nAnGangCardChair42',
            'nAnGangReserved42',
            'nAnGangCardIDs43',
            'nAnGangCardChair43',
            'nAnGangReserved43',
            'nAnGangCardIDs44',
            'nAnGangCardChair44',
            'nAnGangReserved44',
            'nAnGangCardIDs45',
            'nAnGangCardChair45',
            'nAnGangReserved45',
            'nAnGangCardIDs46',
            'nAnGangCardChair46',
            'nAnGangReserved46',
            'nAnGangCount',
            'nPnGangCardIDs11',
            'nPnGangCardChair11',
            'nPnGangReserved11',
            'nPnGangCardIDs12',
            'nPnGangCardChair12',
            'nPnGangReserved12',
            'nPnGangCardIDs13',
            'nPnGangCardChair13',
            'nPnGangReserved13',
            'nPnGangCardIDs14',
            'nPnGangCardChair14',
            'nPnGangReserved14',
            'nPnGangCardIDs15',
            'nPnGangCardChair15',
            'nPnGangReserved15',
            'nPnGangCardIDs16',
            'nPnGangCardChair16',
            'nPnGangReserved16',
            'nPnGangCardIDs21',
            'nPnGangCardChair21',
            'nPnGangReserved21',
            'nPnGangCardIDs22',
            'nPnGangCardChair22',
            'nPnGangReserved22',
            'nPnGangCardIDs23',
            'nPnGangCardChair23',
            'nPnGangReserved23',
            'nPnGangCardIDs24',
            'nPnGangCardChair24',
            'nPnGangReserved24',
            'nPnGangCardIDs25',
            'nPnGangCardChair25',
            'nPnGangReserved25',
            'nPnGangCardIDs26',
            'nPnGangCardChair26',
            'nPnGangReserved26',
            'nPnGangCardIDs31',
            'nPnGangCardChair31',
            'nPnGangReserved31',
            'nPnGangCardIDs32',
            'nPnGangCardChair32',
            'nPnGangReserved32',
            'nPnGangCardIDs33',
            'nPnGangCardChair33',
            'nPnGangReserved33',
            'nPnGangCardIDs34',
            'nPnGangCardChair34',
            'nPnGangReserved34',
            'nPnGangCardIDs35',
            'nPnGangCardChair35',
            'nPnGangReserved35',
            'nPnGangCardIDs36',
            'nPnGangCardChair36',
            'nPnGangReserved36',
            'nPnGangCardIDs41',
            'nPnGangCardChair41',
            'nPnGangReserved41',
            'nPnGangCardIDs42',
            'nPnGangCardChair42',
            'nPnGangReserved42',
            'nPnGangCardIDs43',
            'nPnGangCardChair43',
            'nPnGangReserved43',
            'nPnGangCardIDs44',
            'nPnGangCardChair44',
            'nPnGangReserved44',
            'nPnGangCardIDs45',
            'nPnGangCardChair45',
            'nPnGangReserved45',
            'nPnGangCardIDs46',
            'nPnGangCardChair46',
            'nPnGangReserved46',
            'nPnGangCount',
            'nOutCards',
            'nOutCount',
            'nHuaCards',
            'nHuaCount',
            'nReserved1',
            'nCardsCount',
            'nChairCards',
            'nAskExit',
            'nGangKaiCount',
            'nResultDiff',
            'nTotalResult',
            'bDuanXian',
            'dwUserStatus',
            'nDoubleTimes',
            'nRoleID',
            'nRandRoleDouble',
            'nQuan',
            'bLian',
            'bTing',
            'nChairNo',
            'nTingCardCount',
            'nTingCard',
            'nLeftCardCount',
            'nTingFan',
            'nTingLeastFan',
            'nChangeCardUseUp',
            'nReserved1',
            'bKaiQiDiBao',
            'nDiBaoActiveID',
            'nQiHu',
            'bKaiqiHuanPaiDiscount',
            'nHuanPaiDiscount',
            'nHuanPaiStart',
            'nHuanPaiEnd'
        },
        formatKey = '<AiiiiiiLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLLLLLLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<A32iiiiiiLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLLLLLLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 6272
    },

    GAME_WIN_RESULT={
        lengthMap = {
            [6] = {maxlen = 8},
            [8] = {maxlen = 8},
            [11] = {maxlen = 8},
            [12] = {maxlen = 8},
            [13] = {maxlen = 8},
            [14] = {maxlen = 8},
            [15] = {maxlen = 8},
            [16] = {maxlen = 8},
            [17] = 16,
            [18] = 16,
            [19] = 16,
            [20] = 16,
            [21] = 16,
            [22] = 16,
            [23] = 16,
            [24] = 16,
            [27] = {maxlen = 2},
            [29] = {maxlen = 4},
            [30] = {maxlen = 4},
            [31] = {maxlen = 4},
            [32] = {maxlen = 4},
            [33] = {maxlen = 4},
            [34] = {maxlen = 4},
            [42] = {maxlen = 4},
            [45] = {maxlen = 26},
            [46] = {maxlen = 2},
            [47] = {maxlen = 32,maxwidth = 2,complexType = 'matrix2'},
            [48] = {maxlen = 100},
            [54] = {maxlen = 8},
            maxlen = 54
        },
        nameMap = {
            'dwWinFlags',
            'dwNextFlags',
            'nTotalChairs',
            'nBoutCount',
            'nBanker',
            'nPartnerGroup',
            'bBankWin',
            'nWinPoints',
            'nBaseScore',
            'nBaseDeposit',
            'nOldScores',
            'nOldDeposits',
            'nScoreDiffs',
            'nDepositDiffs',
            'nWinFees',
            'nLevelIDs',
            'szLevelNames1',
            'szLevelNames2',
            'szLevelNames3',
            'szLevelNames4',
            'szLevelNames5',
            'szLevelNames6',
            'szLevelNames7',
            'szLevelNames8',
            'nNextBaseDeposit',
            'nIdlePlayerFlag',
            'nReserved',
            'nNewRound',
            'nMnGangs',
            'nAnGangs',
            'nPnGangs',
            'nHuaCount',
            'nResults',
            'nHuChairs',
            'nLoseChair',
            'nHuChair',
            'nHuCard',
            'nBankerHold',
            'nNextBanker',
            'nChengBaoID',
            'nHuCount',
            'nTingChairs',
            'nTingCount',
            'nDetailCount',
            'nReserved1',
            'nCardsCount',
            'nChairCards',
            'nHuFanType',
            'nBankerGains',
            'bCompleteRole',
            'nRoleGain',
            'nStartGain',
            'nGiveUpHuGain',
            'nReserved1'
        },
        formatKey = '<LLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiAAAAAAAAiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<LLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiA16A16A16A16A16A16A16A16iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 1404
    },

    GIVEUPHU={
        lengthMap = {
            --,
            maxlen = 5
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'bFang'
        },
        formatKey = '<iiiii',
        deformatKey = '<iiiii',
        maxsize = 20
    },

    CARD_CAUGHTNEW={
        lengthMap = {
            [5] = {maxlen = 4},
            [9] = {maxlen = 10},
            [10] = {maxlen = 10},
            [11] = {maxlen = 10},
            [15] = {maxlen = 10},
            [16] = {maxlen = 10},
            [17] = {maxlen = 10},
            [21] = {maxlen = 10},
            [22] = {maxlen = 10},
            [23] = {maxlen = 10},
            [27] = {maxlen = 10},
            [28] = {maxlen = 10},
            [29] = {maxlen = 10},
            [33] = {maxlen = 10},
            [34] = {maxlen = 10},
            [35] = {maxlen = 10},
            [39] = {maxlen = 10},
            [40] = {maxlen = 10},
            [41] = {maxlen = 10},
            [45] = {maxlen = 10},
            [46] = {maxlen = 10},
            [47] = {maxlen = 10},
            [51] = {maxlen = 10},
            [52] = {maxlen = 10},
            [53] = {maxlen = 10},
            [57] = {maxlen = 10},
            [58] = {maxlen = 10},
            [59] = {maxlen = 10},
            [63] = {maxlen = 10},
            [64] = {maxlen = 10},
            [65] = {maxlen = 10},
            [69] = {maxlen = 10},
            [70] = {maxlen = 10},
            [71] = {maxlen = 10},
            [75] = {maxlen = 10},
            [76] = {maxlen = 10},
            [77] = {maxlen = 10},
            [81] = {maxlen = 10},
            [82] = {maxlen = 10},
            [83] = {maxlen = 10},
            maxlen = 84
        },
        nameMap = {
            'nChairNO',
            'nCardID',
            'nCardNO',
            'dwFlags',
            'nReserved',
            'nMjTingCount',
            'nTingCardCount1',
            'nOutCardIndex1',
            'nTingCard1',
            'nLeftCardCount1',
            'nTingFan1',
            'nTingLeastFan1',
            'nTingCardCount2',
            'nOutCardIndex2',
            'nTingCard2',
            'nLeftCardCount2',
            'nTingFan2',
            'nTingLeastFan2',
            'nTingCardCount3',
            'nOutCardIndex3',
            'nTingCard3',
            'nLeftCardCount3',
            'nTingFan3',
            'nTingLeastFan3',
            'nTingCardCount4',
            'nOutCardIndex4',
            'nTingCard4',
            'nLeftCardCount4',
            'nTingFan4',
            'nTingLeastFan4',
            'nTingCardCount5',
            'nOutCardIndex5',
            'nTingCard5',
            'nLeftCardCount5',
            'nTingFan5',
            'nTingLeastFan5',
            'nTingCardCount6',
            'nOutCardIndex6',
            'nTingCard6',
            'nLeftCardCount6',
            'nTingFan6',
            'nTingLeastFan6',
            'nTingCardCount7',
            'nOutCardIndex7',
            'nTingCard7',
            'nLeftCardCount7',
            'nTingFan7',
            'nTingLeastFan7',
            'nTingCardCount8',
            'nOutCardIndex8',
            'nTingCard8',
            'nLeftCardCount8',
            'nTingFan8',
            'nTingLeastFan8',
            'nTingCardCount9',
            'nOutCardIndex9',
            'nTingCard9',
            'nLeftCardCount9',
            'nTingFan9',
            'nTingLeastFan9',
            'nTingCardCount10',
            'nOutCardIndex10',
            'nTingCard10',
            'nLeftCardCount10',
            'nTingFan10',
            'nTingLeastFan10',
            'nTingCardCount11',
            'nOutCardIndex11',
            'nTingCard11',
            'nLeftCardCount11',
            'nTingFan11',
            'nTingLeastFan11',
            'nTingCardCount12',
            'nOutCardIndex12',
            'nTingCard12',
            'nLeftCardCount12',
            'nTingFan12',
            'nTingLeastFan12',
            'nTingCardCount13',
            'nOutCardIndex13',
            'nTingCard13',
            'nLeftCardCount13',
            'nTingFan13',
            'nTingLeastFan13'
        },
        formatKey = '<iiiLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<iiiLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 1752
    },

    CARD_TINGINFO={
        lengthMap = {
            [3] = {maxlen = 10},
            [4] = {maxlen = 10},
            [5] = {maxlen = 10},
            [9] = {maxlen = 10},
            [10] = {maxlen = 10},
            [11] = {maxlen = 10},
            [15] = {maxlen = 10},
            [16] = {maxlen = 10},
            [17] = {maxlen = 10},
            [21] = {maxlen = 10},
            [22] = {maxlen = 10},
            [23] = {maxlen = 10},
            [27] = {maxlen = 10},
            [28] = {maxlen = 10},
            [29] = {maxlen = 10},
            [33] = {maxlen = 10},
            [34] = {maxlen = 10},
            [35] = {maxlen = 10},
            [39] = {maxlen = 10},
            [40] = {maxlen = 10},
            [41] = {maxlen = 10},
            [45] = {maxlen = 10},
            [46] = {maxlen = 10},
            [47] = {maxlen = 10},
            [51] = {maxlen = 10},
            [52] = {maxlen = 10},
            [53] = {maxlen = 10},
            [57] = {maxlen = 10},
            [58] = {maxlen = 10},
            [59] = {maxlen = 10},
            [63] = {maxlen = 10},
            [64] = {maxlen = 10},
            [65] = {maxlen = 10},
            [69] = {maxlen = 10},
            [70] = {maxlen = 10},
            [71] = {maxlen = 10},
            [75] = {maxlen = 10},
            [76] = {maxlen = 10},
            [77] = {maxlen = 10},
            maxlen = 78
        },
        nameMap = {
            'nTingCardCount1',
            'nOutCardIndex1',
            'nTingCard1',
            'nLeftCardCount1',
            'nTingFan1',
            'nTingLeastFan1',
            'nTingCardCount2',
            'nOutCardIndex2',
            'nTingCard2',
            'nLeftCardCount2',
            'nTingFan2',
            'nTingLeastFan2',
            'nTingCardCount3',
            'nOutCardIndex3',
            'nTingCard3',
            'nLeftCardCount3',
            'nTingFan3',
            'nTingLeastFan3',
            'nTingCardCount4',
            'nOutCardIndex4',
            'nTingCard4',
            'nLeftCardCount4',
            'nTingFan4',
            'nTingLeastFan4',
            'nTingCardCount5',
            'nOutCardIndex5',
            'nTingCard5',
            'nLeftCardCount5',
            'nTingFan5',
            'nTingLeastFan5',
            'nTingCardCount6',
            'nOutCardIndex6',
            'nTingCard6',
            'nLeftCardCount6',
            'nTingFan6',
            'nTingLeastFan6',
            'nTingCardCount7',
            'nOutCardIndex7',
            'nTingCard7',
            'nLeftCardCount7',
            'nTingFan7',
            'nTingLeastFan7',
            'nTingCardCount8',
            'nOutCardIndex8',
            'nTingCard8',
            'nLeftCardCount8',
            'nTingFan8',
            'nTingLeastFan8',
            'nTingCardCount9',
            'nOutCardIndex9',
            'nTingCard9',
            'nLeftCardCount9',
            'nTingFan9',
            'nTingLeastFan9',
            'nTingCardCount10',
            'nOutCardIndex10',
            'nTingCard10',
            'nLeftCardCount10',
            'nTingFan10',
            'nTingLeastFan10',
            'nTingCardCount11',
            'nOutCardIndex11',
            'nTingCard11',
            'nLeftCardCount11',
            'nTingFan11',
            'nTingLeastFan11',
            'nTingCardCount12',
            'nOutCardIndex12',
            'nTingCard12',
            'nLeftCardCount12',
            'nTingFan12',
            'nTingLeastFan12',
            'nTingCardCount13',
            'nOutCardIndex13',
            'nTingCard13',
            'nLeftCardCount13',
            'nTingFan13',
            'nTingLeastFan13'
        },
        formatKey = '<iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 1716
    },
}

return MyGameReq
