
local MJGameReq = {
    MJ_START_DATA={
        lengthMap = {
            [1] = 32,
            [17] = {maxlen = 4},
            [32] = {maxlen = 8},
            maxlen = 32
        },
        nameMap = {
            'szSerialNO',
            'nBoutCount',
            'nBaseDeposit',
            'nBaseScore',
            'nBanker',
            'nBankerHold',
            'nCurrentChair',
            'dwStatus',
            'dwCurrentFlags',
            'nFirstCatch',
            'nFirstThrow',
            'nThrowWait',
            'nMaxAutoThrow',
            'nEntrustWait',
            'bNeedDeposit',
            'bForbidDesert',
            'nDices',
            'bQuickCatch',
            'bAllowChi',
            'bAnGangShow',
            'bJokerSortIn',
            'bBaibanNoSort',
            'nBeginNO',
            'nJokerNO',
            'nJokerID',
            'nJokerID2',
            'nFanID',
            'nTailTaken',
            'nCurrentCatch',
            'nPGCHWait',
            'nPGCHWaitEx',
            'nReserved'
        },
        formatKey = '<AiiiiiiLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<A32iiiiiiLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 196
    },

    MJ_PLAY_DATA={
        lengthMap = {
            [1] = {maxlen = 4},
            [3] = {maxlen = 2},
            [4] = {maxlen = 4},
            [6] = {maxlen = 2},
            [7] = {maxlen = 4},
            [9] = {maxlen = 2},
            [10] = {maxlen = 4},
            [12] = {maxlen = 2},
            [13] = {maxlen = 4},
            [15] = {maxlen = 2},
            [16] = {maxlen = 4},
            [18] = {maxlen = 2},
            [19] = {maxlen = 4},
            [21] = {maxlen = 2},
            [22] = {maxlen = 4},
            [24] = {maxlen = 2},
            [25] = {maxlen = 4},
            [27] = {maxlen = 2},
            [28] = {maxlen = 4},
            [30] = {maxlen = 2},
            [31] = {maxlen = 4},
            [33] = {maxlen = 2},
            [34] = {maxlen = 4},
            [36] = {maxlen = 2},
            [37] = {maxlen = 4},
            [39] = {maxlen = 2},
            [40] = {maxlen = 4},
            [42] = {maxlen = 2},
            [43] = {maxlen = 4},
            [45] = {maxlen = 2},
            [46] = {maxlen = 4},
            [48] = {maxlen = 2},
            [49] = {maxlen = 4},
            [51] = {maxlen = 2},
            [52] = {maxlen = 4},
            [54] = {maxlen = 2},
            [55] = {maxlen = 4},
            [57] = {maxlen = 2},
            [58] = {maxlen = 4},
            [60] = {maxlen = 2},
            [61] = {maxlen = 4},
            [63] = {maxlen = 2},
            [64] = {maxlen = 4},
            [66] = {maxlen = 2},
            [67] = {maxlen = 4},
            [69] = {maxlen = 2},
            [70] = {maxlen = 4},
            [72] = {maxlen = 2},
            [73] = {maxlen = 4},
            [74] = {maxlen = 4},
            [76] = {maxlen = 2},
            [77] = {maxlen = 4},
            [79] = {maxlen = 2},
            [80] = {maxlen = 4},
            [82] = {maxlen = 2},
            [83] = {maxlen = 4},
            [85] = {maxlen = 2},
            [86] = {maxlen = 4},
            [88] = {maxlen = 2},
            [89] = {maxlen = 4},
            [91] = {maxlen = 2},
            [92] = {maxlen = 4},
            [94] = {maxlen = 2},
            [95] = {maxlen = 4},
            [97] = {maxlen = 2},
            [98] = {maxlen = 4},
            [100] = {maxlen = 2},
            [101] = {maxlen = 4},
            [103] = {maxlen = 2},
            [104] = {maxlen = 4},
            [106] = {maxlen = 2},
            [107] = {maxlen = 4},
            [109] = {maxlen = 2},
            [110] = {maxlen = 4},
            [112] = {maxlen = 2},
            [113] = {maxlen = 4},
            [115] = {maxlen = 2},
            [116] = {maxlen = 4},
            [118] = {maxlen = 2},
            [119] = {maxlen = 4},
            [121] = {maxlen = 2},
            [122] = {maxlen = 4},
            [124] = {maxlen = 2},
            [125] = {maxlen = 4},
            [127] = {maxlen = 2},
            [128] = {maxlen = 4},
            [130] = {maxlen = 2},
            [131] = {maxlen = 4},
            [133] = {maxlen = 2},
            [134] = {maxlen = 4},
            [136] = {maxlen = 2},
            [137] = {maxlen = 4},
            [139] = {maxlen = 2},
            [140] = {maxlen = 4},
            [142] = {maxlen = 2},
            [143] = {maxlen = 4},
            [145] = {maxlen = 2},
            [146] = {maxlen = 4},
            [147] = {maxlen = 4},
            [149] = {maxlen = 2},
            [150] = {maxlen = 4},
            [152] = {maxlen = 2},
            [153] = {maxlen = 4},
            [155] = {maxlen = 2},
            [156] = {maxlen = 4},
            [158] = {maxlen = 2},
            [159] = {maxlen = 4},
            [161] = {maxlen = 2},
            [162] = {maxlen = 4},
            [164] = {maxlen = 2},
            [165] = {maxlen = 4},
            [167] = {maxlen = 2},
            [168] = {maxlen = 4},
            [170] = {maxlen = 2},
            [171] = {maxlen = 4},
            [173] = {maxlen = 2},
            [174] = {maxlen = 4},
            [176] = {maxlen = 2},
            [177] = {maxlen = 4},
            [179] = {maxlen = 2},
            [180] = {maxlen = 4},
            [182] = {maxlen = 2},
            [183] = {maxlen = 4},
            [185] = {maxlen = 2},
            [186] = {maxlen = 4},
            [188] = {maxlen = 2},
            [189] = {maxlen = 4},
            [191] = {maxlen = 2},
            [192] = {maxlen = 4},
            [194] = {maxlen = 2},
            [195] = {maxlen = 4},
            [197] = {maxlen = 2},
            [198] = {maxlen = 4},
            [200] = {maxlen = 2},
            [201] = {maxlen = 4},
            [203] = {maxlen = 2},
            [204] = {maxlen = 4},
            [206] = {maxlen = 2},
            [207] = {maxlen = 4},
            [209] = {maxlen = 2},
            [210] = {maxlen = 4},
            [212] = {maxlen = 2},
            [213] = {maxlen = 4},
            [215] = {maxlen = 2},
            [216] = {maxlen = 4},
            [218] = {maxlen = 2},
            [219] = {maxlen = 4},
            [220] = {maxlen = 4},
            [222] = {maxlen = 2},
            [223] = {maxlen = 4},
            [225] = {maxlen = 2},
            [226] = {maxlen = 4},
            [228] = {maxlen = 2},
            [229] = {maxlen = 4},
            [231] = {maxlen = 2},
            [232] = {maxlen = 4},
            [234] = {maxlen = 2},
            [235] = {maxlen = 4},
            [237] = {maxlen = 2},
            [238] = {maxlen = 4},
            [240] = {maxlen = 2},
            [241] = {maxlen = 4},
            [243] = {maxlen = 2},
            [244] = {maxlen = 4},
            [246] = {maxlen = 2},
            [247] = {maxlen = 4},
            [249] = {maxlen = 2},
            [250] = {maxlen = 4},
            [252] = {maxlen = 2},
            [253] = {maxlen = 4},
            [255] = {maxlen = 2},
            [256] = {maxlen = 4},
            [258] = {maxlen = 2},
            [259] = {maxlen = 4},
            [261] = {maxlen = 2},
            [262] = {maxlen = 4},
            [264] = {maxlen = 2},
            [265] = {maxlen = 4},
            [267] = {maxlen = 2},
            [268] = {maxlen = 4},
            [270] = {maxlen = 2},
            [271] = {maxlen = 4},
            [273] = {maxlen = 2},
            [274] = {maxlen = 4},
            [276] = {maxlen = 2},
            [277] = {maxlen = 4},
            [279] = {maxlen = 2},
            [280] = {maxlen = 4},
            [282] = {maxlen = 2},
            [283] = {maxlen = 4},
            [285] = {maxlen = 2},
            [286] = {maxlen = 4},
            [288] = {maxlen = 2},
            [289] = {maxlen = 4},
            [291] = {maxlen = 2},
            [292] = {maxlen = 4},
            [293] = {maxlen = 4},
            [295] = {maxlen = 2},
            [296] = {maxlen = 4},
            [298] = {maxlen = 2},
            [299] = {maxlen = 4},
            [301] = {maxlen = 2},
            [302] = {maxlen = 4},
            [304] = {maxlen = 2},
            [305] = {maxlen = 4},
            [307] = {maxlen = 2},
            [308] = {maxlen = 4},
            [310] = {maxlen = 2},
            [311] = {maxlen = 4},
            [313] = {maxlen = 2},
            [314] = {maxlen = 4},
            [316] = {maxlen = 2},
            [317] = {maxlen = 4},
            [319] = {maxlen = 2},
            [320] = {maxlen = 4},
            [322] = {maxlen = 2},
            [323] = {maxlen = 4},
            [325] = {maxlen = 2},
            [326] = {maxlen = 4},
            [328] = {maxlen = 2},
            [329] = {maxlen = 4},
            [331] = {maxlen = 2},
            [332] = {maxlen = 4},
            [334] = {maxlen = 2},
            [335] = {maxlen = 4},
            [337] = {maxlen = 2},
            [338] = {maxlen = 4},
            [340] = {maxlen = 2},
            [341] = {maxlen = 4},
            [343] = {maxlen = 2},
            [344] = {maxlen = 4},
            [346] = {maxlen = 2},
            [347] = {maxlen = 4},
            [349] = {maxlen = 2},
            [350] = {maxlen = 4},
            [352] = {maxlen = 2},
            [353] = {maxlen = 4},
            [355] = {maxlen = 2},
            [356] = {maxlen = 4},
            [358] = {maxlen = 2},
            [359] = {maxlen = 4},
            [361] = {maxlen = 2},
            [362] = {maxlen = 4},
            [364] = {maxlen = 2},
            [365] = {maxlen = 4},
            [366] = {maxlen = 36,maxwidth = 4,complexType = 'matrix2'},
            [367] = {maxlen = 4},
            [368] = {maxlen = 36,maxwidth = 4,complexType = 'matrix2'},
            [369] = {maxlen = 4},
            [370] = {maxlen = 8},
            maxlen = 370
        },
        nameMap = {
            'nPengCardIDs11',
            'nPengCardChair11',
            'nPengReserved11',
            'nPengCardIDs12',
            'nPengCardChair12',
            'nPengReserved12',
            'nPengCardIDs13',
            'nPengCardChair13',
            'nPengReserved13',
            'nPengCardIDs14',
            'nPengCardChair14',
            'nPengReserved14',
            'nPengCardIDs15',
            'nPengCardChair15',
            'nPengReserved15',
            'nPengCardIDs16',
            'nPengCardChair16',
            'nPengReserved16',
            'nPengCardIDs21',
            'nPengCardChair21',
            'nPengReserved21',
            'nPengCardIDs22',
            'nPengCardChair22',
            'nPengReserved22',
            'nPengCardIDs23',
            'nPengCardChair23',
            'nPengReserved23',
            'nPengCardIDs24',
            'nPengCardChair24',
            'nPengReserved24',
            'nPengCardIDs25',
            'nPengCardChair25',
            'nPengReserved25',
            'nPengCardIDs26',
            'nPengCardChair26',
            'nPengReserved26',
            'nPengCardIDs31',
            'nPengCardChair31',
            'nPengReserved31',
            'nPengCardIDs32',
            'nPengCardChair32',
            'nPengReserved32',
            'nPengCardIDs33',
            'nPengCardChair33',
            'nPengReserved33',
            'nPengCardIDs34',
            'nPengCardChair34',
            'nPengReserved34',
            'nPengCardIDs35',
            'nPengCardChair35',
            'nPengReserved35',
            'nPengCardIDs36',
            'nPengCardChair36',
            'nPengReserved36',
            'nPengCardIDs41',
            'nPengCardChair41',
            'nPengReserved41',
            'nPengCardIDs42',
            'nPengCardChair42',
            'nPengReserved42',
            'nPengCardIDs43',
            'nPengCardChair43',
            'nPengReserved43',
            'nPengCardIDs44',
            'nPengCardChair44',
            'nPengReserved44',
            'nPengCardIDs45',
            'nPengCardChair45',
            'nPengReserved45',
            'nPengCardIDs46',
            'nPengCardChair46',
            'nPengReserved46',
            'nPengCount',
            'nChiCardIDs11',
            'nChiCardChair11',
            'nChiReserved11',
            'nChiCardIDs12',
            'nChiCardChair12',
            'nChiReserved12',
            'nChiCardIDs13',
            'nChiCardChair13',
            'nChiReserved13',
            'nChiCardIDs14',
            'nChiCardChair14',
            'nChiReserved14',
            'nChiCardIDs15',
            'nChiCardChair15',
            'nChiReserved15',
            'nChiCardIDs16',
            'nChiCardChair16',
            'nChiReserved16',
            'nChiCardIDs21',
            'nChiCardChair21',
            'nChiReserved21',
            'nChiCardIDs22',
            'nChiCardChair22',
            'nChiReserved22',
            'nChiCardIDs23',
            'nChiCardChair23',
            'nChiReserved23',
            'nChiCardIDs24',
            'nChiCardChair24',
            'nChiReserved24',
            'nChiCardIDs25',
            'nChiCardChair25',
            'nChiReserved25',
            'nChiCardIDs26',
            'nChiCardChair26',
            'nChiReserved26',
            'nChiCardIDs31',
            'nChiCardChair31',
            'nChiReserved31',
            'nChiCardIDs32',
            'nChiCardChair32',
            'nChiReserved32',
            'nChiCardIDs33',
            'nChiCardChair33',
            'nChiReserved33',
            'nChiCardIDs34',
            'nChiCardChair34',
            'nChiReserved34',
            'nChiCardIDs35',
            'nChiCardChair35',
            'nChiReserved35',
            'nChiCardIDs36',
            'nChiCardChair36',
            'nChiReserved36',
            'nChiCardIDs41',
            'nChiCardChair41',
            'nChiReserved41',
            'nChiCardIDs42',
            'nChiCardChair42',
            'nChiReserved42',
            'nChiCardIDs43',
            'nChiCardChair43',
            'nChiReserved43',
            'nChiCardIDs44',
            'nChiCardChair44',
            'nChiReserved44',
            'nChiCardIDs45',
            'nChiCardChair45',
            'nChiReserved45',
            'nChiCardIDs46',
            'nChiCardChair46',
            'nChiReserved46',
            'nChiCount',
            'nMnGangCardIDs11',
            'nMnGangCardChair11',
            'nMnGangReserved11',
            'nMnGangCardIDs12',
            'nMnGangCardChair12',
            'nMnGangReserved12',
            'nMnGangCardIDs13',
            'nMnGangCardChair13',
            'nMnGangReserved13',
            'nMnGangCardIDs14',
            'nMnGangCardChair14',
            'nMnGangReserved14',
            'nMnGangCardIDs15',
            'nMnGangCardChair15',
            'nMnGangReserved15',
            'nMnGangCardIDs16',
            'nMnGangCardChair16',
            'nMnGangReserved16',
            'nMnGangCardIDs21',
            'nMnGangCardChair21',
            'nMnGangReserved21',
            'nMnGangCardIDs22',
            'nMnGangCardChair22',
            'nMnGangReserved22',
            'nMnGangCardIDs23',
            'nMnGangCardChair23',
            'nMnGangReserved23',
            'nMnGangCardIDs24',
            'nMnGangCardChair24',
            'nMnGangReserved24',
            'nMnGangCardIDs25',
            'nMnGangCardChair25',
            'nMnGangReserved25',
            'nMnGangCardIDs26',
            'nMnGangCardChair26',
            'nMnGangReserved26',
            'nMnGangCardIDs31',
            'nMnGangCardChair31',
            'nMnGangReserved31',
            'nMnGangCardIDs32',
            'nMnGangCardChair32',
            'nMnGangReserved32',
            'nMnGangCardIDs33',
            'nMnGangCardChair33',
            'nMnGangReserved33',
            'nMnGangCardIDs34',
            'nMnGangCardChair34',
            'nMnGangReserved34',
            'nMnGangCardIDs35',
            'nMnGangCardChair35',
            'nMnGangReserved35',
            'nMnGangCardIDs36',
            'nMnGangCardChair36',
            'nMnGangReserved36',
            'nMnGangCardIDs41',
            'nMnGangCardChair41',
            'nMnGangReserved41',
            'nMnGangCardIDs42',
            'nMnGangCardChair42',
            'nMnGangReserved42',
            'nMnGangCardIDs43',
            'nMnGangCardChair43',
            'nMnGangReserved43',
            'nMnGangCardIDs44',
            'nMnGangCardChair44',
            'nMnGangReserved44',
            'nMnGangCardIDs45',
            'nMnGangCardChair45',
            'nMnGangReserved45',
            'nMnGangCardIDs46',
            'nMnGangCardChair46',
            'nMnGangReserved46',
            'nMnGangCount',
            'nAnGangCardIDs11',
            'nAnGangCardChair11',
            'nAnGangReserved11',
            'nAnGangCardIDs12',
            'nAnGangCardChair12',
            'nAnGangReserved12',
            'nAnGangCardIDs13',
            'nAnGangCardChair13',
            'nAnGangReserved13',
            'nAnGangCardIDs14',
            'nAnGangCardChair14',
            'nAnGangReserved14',
            'nAnGangCardIDs15',
            'nAnGangCardChair15',
            'nAnGangReserved15',
            'nAnGangCardIDs16',
            'nAnGangCardChair16',
            'nAnGangReserved16',
            'nAnGangCardIDs21',
            'nAnGangCardChair21',
            'nAnGangReserved21',
            'nAnGangCardIDs22',
            'nAnGangCardChair22',
            'nAnGangReserved22',
            'nAnGangCardIDs23',
            'nAnGangCardChair23',
            'nAnGangReserved23',
            'nAnGangCardIDs24',
            'nAnGangCardChair24',
            'nAnGangReserved24',
            'nAnGangCardIDs25',
            'nAnGangCardChair25',
            'nAnGangReserved25',
            'nAnGangCardIDs26',
            'nAnGangCardChair26',
            'nAnGangReserved26',
            'nAnGangCardIDs31',
            'nAnGangCardChair31',
            'nAnGangReserved31',
            'nAnGangCardIDs32',
            'nAnGangCardChair32',
            'nAnGangReserved32',
            'nAnGangCardIDs33',
            'nAnGangCardChair33',
            'nAnGangReserved33',
            'nAnGangCardIDs34',
            'nAnGangCardChair34',
            'nAnGangReserved34',
            'nAnGangCardIDs35',
            'nAnGangCardChair35',
            'nAnGangReserved35',
            'nAnGangCardIDs36',
            'nAnGangCardChair36',
            'nAnGangReserved36',
            'nAnGangCardIDs41',
            'nAnGangCardChair41',
            'nAnGangReserved41',
            'nAnGangCardIDs42',
            'nAnGangCardChair42',
            'nAnGangReserved42',
            'nAnGangCardIDs43',
            'nAnGangCardChair43',
            'nAnGangReserved43',
            'nAnGangCardIDs44',
            'nAnGangCardChair44',
            'nAnGangReserved44',
            'nAnGangCardIDs45',
            'nAnGangCardChair45',
            'nAnGangReserved45',
            'nAnGangCardIDs46',
            'nAnGangCardChair46',
            'nAnGangReserved46',
            'nAnGangCount',
            'nPnGangCardIDs11',
            'nPnGangCardChair11',
            'nPnGangReserved11',
            'nPnGangCardIDs12',
            'nPnGangCardChair12',
            'nPnGangReserved12',
            'nPnGangCardIDs13',
            'nPnGangCardChair13',
            'nPnGangReserved13',
            'nPnGangCardIDs14',
            'nPnGangCardChair14',
            'nPnGangReserved14',
            'nPnGangCardIDs15',
            'nPnGangCardChair15',
            'nPnGangReserved15',
            'nPnGangCardIDs16',
            'nPnGangCardChair16',
            'nPnGangReserved16',
            'nPnGangCardIDs21',
            'nPnGangCardChair21',
            'nPnGangReserved21',
            'nPnGangCardIDs22',
            'nPnGangCardChair22',
            'nPnGangReserved22',
            'nPnGangCardIDs23',
            'nPnGangCardChair23',
            'nPnGangReserved23',
            'nPnGangCardIDs24',
            'nPnGangCardChair24',
            'nPnGangReserved24',
            'nPnGangCardIDs25',
            'nPnGangCardChair25',
            'nPnGangReserved25',
            'nPnGangCardIDs26',
            'nPnGangCardChair26',
            'nPnGangReserved26',
            'nPnGangCardIDs31',
            'nPnGangCardChair31',
            'nPnGangReserved31',
            'nPnGangCardIDs32',
            'nPnGangCardChair32',
            'nPnGangReserved32',
            'nPnGangCardIDs33',
            'nPnGangCardChair33',
            'nPnGangReserved33',
            'nPnGangCardIDs34',
            'nPnGangCardChair34',
            'nPnGangReserved34',
            'nPnGangCardIDs35',
            'nPnGangCardChair35',
            'nPnGangReserved35',
            'nPnGangCardIDs36',
            'nPnGangCardChair36',
            'nPnGangReserved36',
            'nPnGangCardIDs41',
            'nPnGangCardChair41',
            'nPnGangReserved41',
            'nPnGangCardIDs42',
            'nPnGangCardChair42',
            'nPnGangReserved42',
            'nPnGangCardIDs43',
            'nPnGangCardChair43',
            'nPnGangReserved43',
            'nPnGangCardIDs44',
            'nPnGangCardChair44',
            'nPnGangReserved44',
            'nPnGangCardIDs45',
            'nPnGangCardChair45',
            'nPnGangReserved45',
            'nPnGangCardIDs46',
            'nPnGangCardChair46',
            'nPnGangReserved46',
            'nPnGangCount',
            'nOutCards',
            'nOutCount',
            'nHuaCards',
            'nHuaCount',
            'nReserved'
        },
        formatKey = '<iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 4656
    },

    GAME_MSG={
        lengthMap = {
            --,
            maxlen = 5
        },
        nameMap = {
            'nRoomID',
            'nUserID',
            'nMsgID',
            'bNeedEcho',
            'nDatalen'
        },
        formatKey = '<iiiii',
        deformatKey = '<iiiii',
        maxsize = 20
    },

    PGC_CARD={
        lengthMap = {
            [7] = {maxlen = 3},
            [11] = {maxlen = 4},
            maxlen = 11
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nCardChair',
            'nCardID',
            'nBaseIDs',
            'dwFlags',
            'nCardGot',
            'nCardNO',
            'nReserved'
        },
        formatKey = '<iiiiiiiiiLiiiiii',
        deformatKey = '<iiiiiiiiiLiiiiii',
        maxsize = 64
    },

    PREGANG_OK={
        lengthMap = {
            [5] = {maxlen = 4},
            [6] = {maxlen = 4},
            maxlen = 6
        },
        nameMap = {
            'nChairNO',
            'nCardChair',
            'nCardID',
            'dwFlags',
            'dwResults',
            'nReserved'
        },
        formatKey = '<iiiLLLLLiiii',
        deformatKey = '<iiiLLLLLiiii',
        maxsize = 48
    },

    HU_CARD={
        lengthMap = {
            [9] = {maxlen = 4},
            maxlen = 9
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nCardChair',
            'nCardID',
            'dwFlags',
            'dwSubFlags',
            'nReserved'
        },
        formatKey = '<iiiiiiLLiiii',
        deformatKey = '<iiiiiiLLiiii',
        maxsize = 48
    },

    THROW_CARDS={
        lengthMap = {
            [9] = 32,
            [10] = {maxlen = 4},
            [12] = {maxlen = 4},
            [14] = {maxlen = 1},
            maxlen = 14
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'bPassive',
            'nSendTable',
            'nSendChair',
            'nSendUser',
            'szHardID',
            'nReserved',
            'dwCardsType',
            'nReserved1',
            'nCardsCount',
            'nCardIDs'
        },
        formatKey = '<iiiiiiiiAiiiiLiiiiii',
        deformatKey = '<iiiiiiiiA32iiiiLiiiiii',
        maxsize = 108
    },

    CARDS_THROW={
        lengthMap = {
            [7] = {maxlen = 8},
            [10] = {maxlen = 4},
            [12] = {maxlen = 64},
            maxlen = 12
        },
        nameMap = {
            'nUserID',
            'nChairNO',
            'nNextChair',
            'bNextFirst',
            'bNextPass',
            'nRemains',
            'dwFlags',
            'dwCardsType',
            'nThrowCount',
            'nReserved',
            'nCardsCount',
            'nCardIDs'
        },
        formatKey = '<iiiiiiLLLLLLLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<iiiiiiLLLLLLLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 340
    },

    CARD_CAUGHT={
        lengthMap = {
            [5] = {maxlen = 4},
            maxlen = 5
        },
        nameMap = {
            'nChairNO',
            'nCardID',
            'nCardNO',
            'dwFlags',
            'nReserved'
        },
        formatKey = '<iiiLiiii',
        deformatKey = '<iiiLiiii',
        maxsize = 32
    },

    CATCH_CARD={
        lengthMap = {
            [9] = 32,
            [10] = {maxlen = 4},
            [11] = {maxlen = 4},
            maxlen = 11
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'bPassive',
            'nSendTable',
            'nSendChair',
            'nSendUser',
            'szHardID',
            'nReserved',
            'nReserved1'
        },
        formatKey = '<iiiiiiiiAiiiiiiii',
        deformatKey = '<iiiiiiiiA32iiiiiiii',
        maxsize = 96
    },

    GUO_CARD={
        lengthMap = {
            [7] = {maxlen = 4},
            maxlen = 7
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nCardChair',
            'nCardID',
            'nReserved'
        },
        formatKey = '<iiiiiiiiii',
        deformatKey = '<iiiiiiiiii',
        maxsize = 40
    },

    HUA_CARD={
        lengthMap = {
            [8] = {maxlen = 4},
            maxlen = 8
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nCardID',
            'nCardGot',
            'nCardNO',
            'nReserved'
        },
        formatKey = '<iiiiiiiiiii',
        deformatKey = '<iiiiiiiiiii',
        maxsize = 44
    },

    CARD_HUA={
        lengthMap = {
            [8] = {maxlen = 4},
            maxlen = 8
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nCardID',
            'nCardGot',
            'nCardNO',
            'nReserved'
        },
        formatKey = '<iiiiiiiiiii',
        deformatKey = '<iiiiiiiiiii',
        maxsize = 44
    },

    GAME_WIN_MJ={
        lengthMap = {
            [6] = {maxlen = 8},
            [8] = {maxlen = 8},
            [11] = {maxlen = 8},
            [12] = {maxlen = 8},
            [13] = {maxlen = 8},
            [14] = {maxlen = 8},
            [15] = {maxlen = 8},
            [16] = {maxlen = 8},
            [17] = 16,
            [18] = 16,
            [19] = 16,
            [20] = 16,
            [21] = 16,
            [22] = 16,
            [23] = 16,
            [24] = 16,
            [27] = {maxlen = 2},
            [29] = {maxlen = 4},
            [30] = {maxlen = 4},
            [31] = {maxlen = 4},
            [32] = {maxlen = 4},
            [33] = {maxlen = 4},
            [34] = {maxlen = 4},
            [42] = {maxlen = 4},
            [45] = {maxlen = 26},
            maxlen = 45
        },
        nameMap = {
            'dwWinFlags',
            'dwNextFlags',
            'nTotalChairs',
            'nBoutCount',
            'nBanker',
            'nPartnerGroup',
            'bBankWin',
            'nWinPoints',
            'nBaseScore',
            'nBaseDeposit',
            'nOldScores',
            'nOldDeposits',
            'nScoreDiffs',
            'nDepositDiffs',
            'nWinFees',
            'nLevelIDs',
            'szLevelNames1',
            'szLevelNames2',
            'szLevelNames3',
            'szLevelNames4',
            'szLevelNames5',
            'szLevelNames6',
            'szLevelNames7',
            'szLevelNames8',
            'nNextBaseDeposit',
            'nIdlePlayerFlag',
            'nReserved',
            'nNewRound',
            'nMnGangs',
            'nAnGangs',
            'nPnGangs',
            'nHuaCount',
            'nResults',
            'nHuChairs',
            'nLoseChair',
            'nHuChair',
            'nHuCard',
            'nBankerHold',
            'nNextBanker',
            'nChengBaoID',
            'nHuCount',
            'nTingChairs',
            'nTingCount',
            'nDetailCount',
            'nReserved1'
        },
        formatKey = '<LLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiAAAAAAAAiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<LLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiA16A16A16A16A16A16A16A16iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 688
    },

    GAME_TABLE_INFO={
        lengthMap = {
            [1] = 32,
            [17] = {maxlen = 4},
            [32] = {maxlen = 8},
            [33] = {maxlen = 4},
            [35] = {maxlen = 2},
            [36] = {maxlen = 4},
            [38] = {maxlen = 2},
            [39] = {maxlen = 4},
            [41] = {maxlen = 2},
            [42] = {maxlen = 4},
            [44] = {maxlen = 2},
            [45] = {maxlen = 4},
            [47] = {maxlen = 2},
            [48] = {maxlen = 4},
            [49] = {maxlen = 36,maxwidth = 4,complexType = 'matrix2'},
            [50] = {maxlen = 4},
            [51] = {maxlen = 36,maxwidth = 4,complexType = 'matrix2'},
            [52] = {maxlen = 4},
            [53] = {maxlen = 8},
            [54] = {maxlen = 4},
            [55] = {maxlen = 32},
            [56] = {maxlen = 4},
            [57] = {maxlen = 100,maxwidth = 4,complexType = 'matrix2'},
            [58] = {maxlen = 4},
            [60] = {maxlen = 4},
            [61] = {maxlen = 4},
            maxlen = 61
        },
        nameMap = {
            'szSerialNO',
            'nBoutCount',
            'nBaseDeposit',
            'nBaseScore',
            'nBanker',
            'nBankerHold',
            'nCurrentChair',
            'dwStatus',
            'dwCurrentFlags',
            'nFirstCatch',
            'nFirstThrow',
            'nThrowWait',
            'nMaxAutoThrow',
            'nEntrustWait',
            'bNeedDeposit',
            'bForbidDesert',
            'nDices',
            'bQuickCatch',
            'bAllowChi',
            'bAnGangShow',
            'bJokerSortIn',
            'bBaibanNoSort',
            'nBeginNO',
            'nJokerNO',
            'nJokerID',
            'nJokerID2',
            'nFanID',
            'nTailTaken',
            'nCurrentCatch',
            'nPGCHWait',
            'nPGCHWaitEx',
            'nReserved',
            'nCardIDs',
            'nCardChair',
            'nReserved1',
            'nCardIDs1',
            'nCardChair1',
            'nReserved1',
            'nCardIDs1',
            'nCardChair1',
            'nReserved1',
            'nCardIDs1',
            'nCardChair1',
            'nReserved1',
            'nCardIDs1',
            'nCardChair1',
            'nReserved1',
            'nPnGangCount',
            'nOutCards',
            'nOutCount',
            'nHuaCards',
            'nHuaCount',
            'nReserved1',
            'nCardsCount',
            'nChairCards',
            'nAskExit',
            'Score',
            'TotalScore',
            'nGangKaiCount',
            'bDuanXian',
            'nReserved1'
        },
        formatKey = '<AiiiiiiLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<A32iiiiiiLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 3380
    },

    MJ_ENTER_INFO={
        lengthMap = {
            [6] = {maxlen = 8},
            [9] = {maxlen = 7},
            [10] = {maxlen = 30,maxwidth = 8,complexType = 'matrix2'},
            [11] = {maxlen = 8},
            [12] = {maxlen = 4},
            maxlen = 12
        },
        nameMap = {
            'nRoomID',
            'nTableNO',
            'nTotalChair',
            'nBaseScore',
            'nBaseDeposit',
            'dwUserStatus',
            'nBout',
            'nKickOffTime',
            'nReserved',
            'nResultDiff',
            'nTotalResult',
            'nReserve'
        },
        formatKey = '<iiiiiLLLLLLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<iiiiiLLLLLLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 1096
    },
}

return MJGameReq