
if nil == cc or nil == cc.exports then
    return
end


cc.exports.BaseGameDef                      = {
    BASEGAME_MYDRAWINDEX                    = 1,
    BASEGAME_MAX_PLAYERS                    = 8,
    BASEGAME_MAX_CARDS                      = 64,

    BASEGAME_MSG_GREETING                   = 0,
    BASEGAME_MSG_REQUEST                    = 1,
    BASEGAME_MSG_RESPONSE                   = 2,
    BASEGAME_MSG_ACKNOWLEDGE                = 3,

    BASEGAME_UR_REQ_BASE                    = 0,
    BASEGAME_UR_SOCKET_CLOSE                = 1,
    BASEGAME_UR_SOCKET_ERROR                = 2,
    BASEGAME_UR_SOCKET_CONNECT              = 3,
    BASEGAME_UR_SOCKET_GRACEFULLY_ERROR     = 4,
    BASEGAME_UR_RESPONSE_TIMEOUT            = 1030,

    BASEGAME_UR_OPERATE_SUCCEEDED           = 10,
    BASEGAME_UR_OPERATE_FAILED              = 10100,

    BASEGAME_US_GAME_STARTED                = 0x00000002,

    -- waitting session
    BASEGAME_WAITING_NOTHING                = 0,
    BASEGAME_WAITING_CHECK_VERSION          = 1,
    BASEGAME_WAITING_ENTER_GAME             = 2,
    BASEGAME_WAITING_ENTER_GAME_OK          = 2,
    BASEGAME_WAITING_ENTER_GAME_DXXW        = 3,
    BASEGAME_WAITING_ENTER_GAME_IDLE        = 4,
    BASEGAME_WAITING_START_GAME             = 5,
    BASEGAME_WAITING_ASK_RANDOM_TABLE       = 6,
    BASEGAME_WAITING_LEAVE_GAME             = 7,
    BASEGAME_WAITING_ASK_NEW_TABLE          = 8,
    BASEGAME_WAITING_GET_TABLE_INFO         = 9,
    BASEGAME_WAITING_LOOK_SAFE_DEPOSIT      = 10,
    BASEGAME_WAITING_LOOK_BACK_DEPOSIT      = 11,
    BASEGAME_WAITING_TAKE_SAFE_DEPOSIT      = 12,
    BASEGAME_WAITING_TAKE_BACK_DEPOSIT      = 13,
    BASEGAME_WAITING_SAVE_SAFE_DEPOSIT      = 14,
    BASEGAME_WAITING_SAVE_BACK_DEPOSIT      = 15,
    BASEGAME_WAITING_TAKE_SAFE_RNDKEY       = 16,
    BASEGAME_WAITING_QUERY_BREAK            = 17,
    BASEGAME_WAITING_GET_WELFARE_CONFIG     = 18,
    BASEGAME_WAITING_APPLY_WELFARE          = 19,

    -- error response
    BASEGAME_GR_SERVICE_BUSY                = 50998,
    BASEGAME_GR_DEPOSIT_NOTENOUGH           = 60005,
    BASEGAME_GR_NO_THIS_FUNCTION            = 60017,
    BASEGAME_GR_SYSTEM_LOCKED               = 60019,
    BASEGAME_GR_TOKENID_MISMATCH            = 60023,
    BASEGAME_GR_HARDID_MISMATCHEX           = 60027,
    BASEGAME_GR_CONTINUE_PWDWRONG           = 60029,
    BASEGAME_GR_ERROR_INFOMATION            = 60031,
    BASEGAME_GR_PWDLEN_INVALID              = 60038,
    BASEGAME_GR_NEED_LOGON                  = 60039,
    BASEGAME_GR_ROOM_NOT_EXIST              = 60040,
    BASEGAME_GR_NODEPOSIT_GAME              = 60042,
    BASEGAME_GR_ROOM_CLOSED                 = 60050,
    BASEGAME_GR_BOUT_NOTENOUGH              = 60070,
    BASEGAME_GR_TIMECOST_NOTENOUGH          = 60071,
    BASEGAME_GR_ROOM_NOT_OPENED             = 60078,
    BASEGAME_GR_NEED_PLAYING                = 60084,
    BASEGAME_GR_NO_MOBILEUSER               = 60085,
    BASEGAME_GR_INPUTLIMIT_DAILY            = 60086,
    BASEGAME_GR_KEEPDEPOSIT_LIMIT           = 60092,
    BASEGAME_GR_INPUTLIMIT_MONTHLY          = 60095,
    BASEGAME_GR_USER_FORBIDDEN              = 60101,

    -- request (from game client)
    BASEGAME_MOBILE_REQ_BASE                = 300000,
    BASEGAME_MR_GET_VERSION                 = 300001,
    BASEGAME_MR_CHECK_VERSION               = 300002,
    BASEGAME_MR_ENTER_BACKGROUND            = 300050,
    BASEGAME_MR_ENTER_FOREGROUND            = 300051,

    BASEGAME_GAME_REQ_BASE                  = 200000,

    BASEGAME_GR_LOOK_SAFE_DEPOSIT           = 200040,
    BASEGAME_GR_TAKE_SAFE_DEPOSIT           = 200041,
    BASEGAME_GR_SAVE_SAFE_DEPOSIT           = 200042,
    BASEGAME_GR_TAKE_SAFE_RNDKEY            = 200043,
    BASEGAME_GR_LOOK_BACKDEPOSIT_INGAME     = 200044,
    BASEGAME_GR_TAKE_BACKDEPOSIT_INGAME     = 200045,
    BASEGAME_GR_SAVE_BACKDEPOSIT_INGAME     = 200046,

    BASEGAME_GR_ENTER_GAME                  = 200110,
    BASEGAME_GR_GAME_PULSE                  = 201020,
    BASEGAME_GR_LEAVE_GAME                  = 201125,
    BASEGAME_GR_GET_TABLE_INFO              = 201140,
    BASEGAME_GR_START_GAME                  = 201165,
    BASEGAME_GR_CHAT_TO_TABLE               = 201211,
    BASEGAME_GR_ASK_NEW_TABLECHAIR          = 201300,
    BASEGAME_GR_ASK_RANDOM_TABLE            = 201302,

    -- response (from server)
    BASEGAME_GR_WAIT_FEW_SECONDS            = 210050,
    BASEGAME_GR_HARDID_MISMATCH             = 210060,
    BASEGAME_GR_ROOM_TOKENID_MISMATCH       = 210070,
    BASEGAME_GR_ROOMTABLECHAIR_MISMATCH     = 210078,
    BASEGAME_GR_LEAVEGAME_TOOFAST           = 210085,
    BASEGAME_GR_LEAVEGAME_PLAYING           = 210086,

    BASEGAME_GR_RESPONE_ENTER_GAME_OK       = 210200,
    BASEGAME_GR_RESPONE_ENTER_GAME_DXXW     = 210210,
    BASEGAME_GR_RESPONE_ENTER_GAME_IDLE     = 210220,

    BASEGAME_GR_RESPONE_DEPOSIT_NOTENOUGH   = 210541,
    BASEGAME_GR_RESPONE_DEPOSIT_TOOHIGH     = 210542,
    BASEGAME_GR_RESPONE_ASKNEWTABLE_SPANSHORT= 210220,
    
    -- nofication (to game client)
    BASEGAME_GR_PLAYER_START_GAME           = 201160,
    BASEGAME_GR_GAME_ABORT                  = 211000,
    BASEGAME_GR_PLAYER_ABORT                = 211010,
    BASEGAME_GR_PLAYER_ENTER                = 211011,
    BASEGAME_GR_START_SOLOTABLE             = 211028,
    BASEGAME_GR_ALL_STANDBY                 = 211030,
    BASEGAME_GR_GAME_START                  = 211040,
    BASEGAME_GR_DEPOSIT_NOT_ENOUGH          = 211110,
    BASEGAME_GR_SCORE_NOT_ENOUGH            = 211130,
    BASEGAME_GR_SCORE_TOO_HIGH              = 211132,
    BASEGAME_GR_USER_BOUT_TOO_HIGH          = 211134,
    BASEGAME_GR_TABLE_BOUT_TOO_HIGH         = 211136,
    BASEGAME_GR_CHAT_FROM_TALBE             = 211200,
    BASEGAME_GR_WAIT_NEWTABLE               = 211300,
    BASEGAME_GR_USER_DEPOSIT_EVENT          = 211600,
    BASEGAME_GR_USER_POSITION               = 211700,
    BASEGAME_GR_KICKOFF_IDLEPLAYER          = 211800,
    BASEGAME_GR_OLD_VER_EXEMAJORVER         = 212000,
    BASEGAME_GR_OLD_VER_EXEMINORVER         = 212001,
    BASEGAME_GR_OLD_VER_EXEBUILDNO          = 212002,
    BASEGAME_GR_NEW_VER_EXEMAJORVER         = 212003,
    BASEGAME_GR_NEW_VER_EXEMINORVER         = 212004,
    BASEGAME_GR_NEW_VER_EXEBUILDNO          = 212005,
    BASEGAME_GR_SAFEBOX_GAME_READY          = 229600,
    BASEGAME_GR_SAFEBOX_GAME_PLAYING        = 229601,
    BASEGAME_GR_SAFEBOX_DEPOSIT_DIFFER      = 229602,
    BASEGAME_GR_SAFEBOX_DEPOSIT_MIN         = 229603,
    BASEGAME_GR_SAFEBOX_DEPOSIT_MAX         = 229604,
    
    -- RoomConfig
    BASEGAME_RC_DARK_ROOM                   = 0x00000001,
    BASEGAME_RC_RANDOM_ROOM                 = 0x00000002,
    BASEGAME_RC_SOLO_ROOM                   = 0x00000040,
    BASEGAME_RC_LEAVEALONE                  = 0x00000080,
    BASEGAME_RC_VARIABLE_CHAIR              = 0x00001000,
    BASEGAME_RC_TAKEDEPOSITINGAME           = 0x01000000,

    BASEGAME_TS_PLAYING_GAME                = 0x00000001,
    BASEGAME_TS_WAITING_START               = 0x00000002,
    BASEGAME_TS_WAITING_AUCTION             = 0x00000010,
    BASEGAME_TS_WAITING_CALL                = 0x00000020,
    BASEGAME_TS_WAITING_BOTTOM              = 0x00000040,
    BASEGAME_TS_WAITING_THROW               = 0x00000100,
    BASEGAME_TS_WAITING_BIGGER              = 0x00000200,
    BASEGAME_TS_WAITING_CATCH               = 0x00000400,
    BASEGAME_TS_WAITING_REPLY               = 0x00001000,

    BASEGAME_USER_LOOK_SAFE_DEPOSIT         = 0,
    BASEGAME_USER_TAKE_SAFE_DEPOSIT         = 1,
    BASEGAME_USER_SAVE_SAFE_DEPOSIT         = 2,
    BASEGAME_USER_APPLY_BASEWELFARE         = 3,
    
    BASEGAME_FLAG_CHAT_RESERVED             = 0x00000001,
    BASEGAME_FLAG_CHAT_SYSNOTIFY            = 0x00000002,
    BASEGAME_FLAG_CHAT_ADMINMSG             = 0x00000004,
    BASEGAME_FLAG_CHAT_PLAYERMSG            = 0x00000008,

    -- RoomOption
    BASEGAME_RO_NEED_DEPOSIT                = 0x00000004,

    BASEGAME_FLAG_SUPPORT_KEEPDEPOSIT_EX    = 0x00000001,
    BASEGAME_FLAG_SUPPORT_MONTHLY_LIMIT_EX  = 0x00000002,
}

local GamePublicInterface = import("src.app.Game.mMyGame.GamePublicInterface")

if GamePublicInterface and GamePublicInterface:IS_FRAME_1() then
    cc.exports.BaseGameDef.BASEGAME_GR_START_GAME                   = 201161
    cc.exports.BaseGameDef.BASEGAME_GR_USER_DEPOSIT_EVENT           = 211420
    cc.exports.BaseGameDef.BASEGAME_TS_WAITING_AUCTION              = 0x00000002
    cc.exports.BaseGameDef.BASEGAME_TS_WAITING_CALL                 = 0x00000004
    cc.exports.BaseGameDef.BASEGAME_TS_WAITING_BOTTOM               = 0x00000008

    cc.exports.BaseGameDef.BASEGAME_GR_RESPONE_DEPOSIT_NOTENOUGH    = 210090
    cc.exports.BaseGameDef.BASEGAME_GR_RESPONE_DEPOSIT_TOOHIGH      = 210091
    cc.exports.BaseGameDef.BASEGAME_GR_RESPONE_ASKNEWTABLE_SPANSHORT= 210092
    cc.exports.BaseGameDef.BASEGAME_GR_SAFEBOX_GAME_READY           = 211421
    cc.exports.BaseGameDef.BASEGAME_GR_SAFEBOX_GAME_PLAYING         = 211422
    cc.exports.BaseGameDef.BASEGAME_GR_SAFEBOX_DEPOSIT_DIFFER       = 211423
    cc.exports.BaseGameDef.BASEGAME_GR_SAFEBOX_DEPOSIT_MIN          = 211424
    cc.exports.BaseGameDef.BASEGAME_GR_SAFEBOX_DEPOSIT_MAX          = 211425
end

return cc.exports.BaseGameDef
